version: '2'
services:
  weblate:
    image: quay.io/appuio/weblate:techlab
    links:
      - database
      - cache
    ports:
      - "8080:8080"
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./weblate/environment
    restart: always
    depends_on:
      - database
      - cache
  database:
    image: postgres:9.4
    env_file:
      - ./weblate/environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: memcached:1.4
    restart: always
volumes:
  weblate-data: {}
  postgres-data: {}
